name: example
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.10.0
description: Example application for misskey_mfm_renderer package.
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  misskey_mfm_renderer:
    path: ../
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.33.0
  pubspec_dependency_sorter: ^1.0.5
flutter:
  uses-material-design: true
