name: misskey_mfm_renderer
version: 0.0.1
environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"
description: A new Flutter package project.
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.35.0
  pubspec_dependency_sorter: ^1.0.5
flutter: null
